name: Android CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up Android SDK License
        run: yes | /usr/local/lib/android/sdk/tools/bin/sdkmanager --licenses

      - name: Build with Gradle
        run: ./gradlew spotlessCheck lint build

      - name: Upload build reports
        uses: actions/upload-artifact@v2
        with:
          name: build-reports
          path: ./app/build/reports

      - name: Upload build apk
        uses: actions/upload-artifact@v2
        with:
          name: build-mapping
          path: ./app/build/outputs/apk
